### ISSUE TITLE
error when using veff2 with basenji

### ISSUE THREAD

**Issue by cmlakhan** [kipoi/kipoi-veff2#35]
I am trying to use this VEF tool but I'm getting an error when I try it on the Basenji model.  This is my code below:
```
from kipoi_veff2 import variant_centered


vcf_file = input.vcf'
fasta_file = hg19.fa'
model_name = 'Basenji'

output_file = 'output.vcf'


model_group = model_name.split("/")[0]


model_group_config_dict = (variant_centered.VARIANT_CENTERED_MODEL_GROUP_CONFIGS.get(model_group, {})
                           )

model_config = variant_centered.get_model_config(model_name, **model_group_config_dict)

#model_config.batch_size = 5

variant_centered.score_variants(
    model_config=model_config,
    vcf_file=vcf_file,
    fasta_file=fasta_file,
    output_file=output_file,
)
```

However, I get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/gpfs/commons/home/clakhani/gitProjects/kipoi-veff2/kipoi_veff2/variant_centered.py", line 251, in score_variants
    vcf_file, fasta_file, sequence_length, model_config.batch_size
  File "/gpfs/commons/home/clakhani/gitProjects/kipoi-veff2/kipoi_veff2/variant_centered.py", line 204, in batch_dataloader
    for interval in intervals
  File "/gpfs/commons/home/clakhani/gitProjects/kipoi-veff2/kipoi_veff2/variant_centered.py", line 204, in <listcomp>
    for interval in intervals
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/kipoiseq/extractors/vcf_seq.py", line 162, in extract
    seq = self._fetch(interval, istart, iend)
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/kipoiseq/extractors/vcf_seq.py", line 260, in _fetch
    Interval(interval.chrom, istart, iend))
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/kipoiseq/extractors/fasta.py", line 49, in extract
    rc=rc
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 1046, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 635, in fetch
    seq = self.from_file(name, start, end)
  File "/gpfs/commons/home/clakhani/.conda/envs/kipoi_veff2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 657, in from_file
    "Requested start coordinate must be greater than 1.")
pyfaidx.FetchError: Requested start coordinate must be greater than 1.



```

Any idea why this might be the case?

**Comment by haimasree** [comment]
Hello, sorry about the late reply. Unfortunately I have not seen this error before. However, it seems there is a discrepancy between your vcf file and what pyfaidx expects. Specifically, it is coming from - [this](https://github.com/kipoi/kipoiseq/blob/master/kipoiseq/extractors/fasta.py#L45) and [this](https://github.com/mdshw5/pyfaidx/blob/v0.5.9.5/pyfaidx/__init__.py#L655-L657). Maybe printing out the start and end coordinate of the specific interval in question can offer some more idea?

**Comment by cmlakhan** [comment]
Thanks, I will look into it out and let you know what happens.

**Comment by haimasree** [comment]
Hi! Its been a while and I was wondering if you still need help. If your issue has been resolved may I close it?

**Comment by haimasree** [comment]
Closing due to no acitivity
